apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  namespace: default
spec:
  template:
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: otel
