apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
configMapGenerator:
  - name: otel
    envs:
      - staging.env
generatorOptions:
  disableNameSuffixHash: true
