apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: library
          envFrom:
            - configMapRef:
                name: otel
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health
              port: http
