apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
configMapGenerator:
- envs:
  - otel.env
  name: otel
images:
- name: kurtis/library
  newName: kurtis/library
  newTag: 1.0.0
namespace: demo
